// SUBSCRIBE ACTIONS 

export const SUSCRIBE_REQUESTED = "SUSCRIBE_REQUESTED";
export const SUSCRIBE_SUCCESS = "SUSCRIBE_SUCCESS";
export const SUSCRIBE_ERROR = "SUSCRIBE_ERROR";

export const RESET_DATA = "RESET_DATA";